const { app, BrowserWindow, ipcMain, dialog, Menu, Tray, nativeImage, Notification } = require('electron')
const path = require('path')
const fs = require('fs')
const https = require('https')
const http = require('http')
const { spawn } = require('child_process')

/* ── State ── */
let mainWindow = null
let tray = null
let isQuitting = false
const isDev = !!process.env.VITE_DEV_SERVER_URL

/* ── Window creation ── */

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    minWidth: 960,
    minHeight: 640,
    frame: false,               // Custom title bar
    titleBarStyle: 'hidden',    // macOS: hide native title bar
    backgroundColor: '#0F172A', // Match dark theme surface-root
    show: false,                // Wait until ready-to-show to avoid white flash
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  })

  /* ── Load content ── */
  if (isDev) {
    mainWindow.loadURL(process.env.VITE_DEV_SERVER_URL)
    mainWindow.webContents.openDevTools({ mode: 'detach' })
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'))
  }

  /* ── Show when ready (avoid white flash) ── */
  mainWindow.once('ready-to-show', () => {
    mainWindow.show()
  })

  mainWindow.on('close', (event) => {
    if (!isQuitting) {
      event.preventDefault()
      mainWindow.hide()
    }
  })

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

/* ── Tray ── */

function createTray() {
  // Load tray icon (generated by gen-tray-icon.cjs, or use a fallback)
  const iconPath = path.join(__dirname, 'tray-icon.png')
  let icon
  if (fs.existsSync(iconPath)) {
    icon = nativeImage.createFromPath(iconPath)
  } else {
    // Fallback: create a simple 16×16 pink square PNG
    icon = nativeImage.createEmpty()
    // Create a minimal pink 16×16 data URL for the tray
    icon = nativeImage.createFromDataURL(
      'data:image/png;base64,' +
      'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAATklEQVQ4y2P4z0ABYIAC+C9AHAYGUuIAhQGmgOyGMBASB+SUASYDdgyQBQyExAF5ZUDDTAwMTAwkJyoGcsoAWRZCoQBAOBAOBAV1AADm/xdLPG4n7wAAAABJRU5ErkJggg=='
    )
    icon = icon.resize({ width: 16, height: 16 })
  }

  tray = new Tray(icon)
  tray.setToolTip('BilibiliDown')

  // Double-click to show window
  tray.on('double-click', () => {
    showAndFocusWindow()
  })

  // Single-click also shows (Windows convention)
  tray.on('click', () => {
    showAndFocusWindow()
  })

  // Build context menu
  updateTrayMenu()
}

function showAndFocusWindow() {
  if (!mainWindow) return
  if (mainWindow.isMinimized()) mainWindow.restore()
  if (!mainWindow.isVisible()) mainWindow.show()
  mainWindow.focus()
}

function updateTrayMenu(downloadStats) {
  if (!tray) return

  const activeCount = downloadStats?.active ?? 0
  const completedCount = downloadStats?.completed ?? 0
  const totalCount = downloadStats?.total ?? 0

  let statusLabel = '下载队列: 无任务'
  if (totalCount > 0) {
    statusLabel = `下载: ${completedCount}/${totalCount} 完成`
    if (activeCount > 0) statusLabel += ` (${activeCount} 进行中)`
  }

  const contextMenu = Menu.buildFromTemplate([
    {
      label: '显示窗口',
      click: () => showAndFocusWindow(),
    },
    {
      label: statusLabel,
      enabled: false,
    },
    { type: 'separator' },
    {
      label: '退出 BilibiliDown',
      click: () => {
        isQuitting = true
        app.quit()
      },
    },
  ])

  tray.setContextMenu(contextMenu)
}

/* ── IPC: tray notifications ── */

ipcMain.handle('tray:updateStats', (_event, stats) => {
  updateTrayMenu(stats)

  // Update tooltip with download info
  if (tray && stats && stats.total > 0) {
    const tooltip = stats.active > 0
      ? `BilibiliDown — 下载中 ${stats.completed}/${stats.total}`
      : `BilibiliDown — ${stats.completed}/${stats.total} 已完成`
    tray.setToolTip(tooltip)
  } else if (tray) {
    tray.setToolTip('BilibiliDown')
  }
})

ipcMain.handle('tray:notification', (_event, { title, body }) => {
  // Use native Notification if supported
  if (Notification.isSupported()) {
    const n = new Notification({
      title: title || 'BilibiliDown',
      body: body || '',
      icon: tray ? tray.icon : undefined,
    })
    n.show()
  }
})

/* ── IPC: app quit ── */

ipcMain.handle('app:quit', () => {
  isQuitting = true
  app.quit()
})

/* ── IPC handlers: window controls ── */

ipcMain.handle('window:minimize', () => {
  if (mainWindow) mainWindow.minimize()
})

ipcMain.handle('window:maximize', () => {
  if (mainWindow) {
    if (mainWindow.isMaximized()) {
      mainWindow.unmaximize()
    } else {
      mainWindow.maximize()
    }
  }
})

ipcMain.handle('window:close', () => {
  if (mainWindow) mainWindow.close()
})

ipcMain.handle('window:isMaximized', () => {
  return mainWindow ? mainWindow.isMaximized() : false
})

/* ── IPC handlers: dialogs ── */

ipcMain.handle('dialog:selectDirectory', async () => {
  if (!mainWindow) return null
  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ['openDirectory'],
    title: '选择下载目录',
  })
  return result.canceled ? null : result.filePaths[0]
})

ipcMain.handle('dialog:saveFile', async (_event, defaultName) => {
  if (!mainWindow) return null
  const result = await dialog.showSaveDialog(mainWindow, {
    title: '保存文件',
    defaultPath: defaultName,
    filters: [
      { name: '视频文件', extensions: ['mp4', 'flv', 'mkv'] },
      { name: '音频文件', extensions: ['mp3', 'aac', 'flac', 'm4a'] },
      { name: '所有文件', extensions: ['*'] },
    ],
  })
  return result.canceled ? null : result.filePath
})

/* ── IPC handlers: app info ── */

ipcMain.handle('app:version', () => app.getVersion())
ipcMain.handle('app:platform', () => process.platform)

/* ── IPC handlers: download file to disk ── */

/**
 * Download a file from a URL and save it to disk.
 *
 * Input: { url, filePath, headers?, referer? }
 * Output: { success, filePath, size, error? }
 *
 * Uses Node.js http/https for direct streaming — no need to pass
 * large blobs through IPC. Reports progress back via ipc event.
 */
ipcMain.handle('download:saveToDisk', async (_event, { url, filePath, headers, referer }) => {
  return new Promise((resolve) => {
    try {
      // Parse the URL to determine http vs https
      const parsedUrl = new URL(url)
      const mod = parsedUrl.protocol === 'https:' ? https : http

      const requestHeaders = {
        Referer: referer || 'https://www.bilibili.com',
        Origin: 'https://www.bilibili.com',
        'User-Agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        ...(headers || {}),
      }

      const req = mod.request(
        url,
        {
          method: 'GET',
          headers: requestHeaders,
        },
        (res) => {
          // Handle redirects
          if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
            // Follow redirect
            const redirectUrl = new URL(res.headers.location, url).toString()
            // Recursively call — use the same handler
            const subReq = (redirectUrl.startsWith('https:') ? https : http).request(
              redirectUrl,
              { method: 'GET', headers: requestHeaders },
              (redirectRes) => {
                streamToFile(redirectRes, filePath, resolve)
              }
            )
            subReq.on('error', (err) => resolve({ success: false, error: err.message }))
            subReq.end()
            return
          }

          if (res.statusCode !== 200) {
            resolve({ success: false, error: `HTTP ${res.statusCode}: ${res.statusMessage}` })
            return
          }

          streamToFile(res, filePath, resolve)
        }
      )

      req.on('error', (err) => {
        resolve({ success: false, error: err.message })
      })

      req.setTimeout(300000, () => {
        req.destroy()
        resolve({ success: false, error: '下载超时' })
      })

      req.end()
    } catch (err) {
      resolve({ success: false, error: err.message })
    }
  })
})

/**
 * Stream an HTTP response to a file, with progress reporting.
 */
function streamToFile(response, filePath, resolve) {
  const totalSize = parseInt(response.headers['content-length'] || '0', 10)
  let downloadedSize = 0
  let lastReportTime = Date.now()
  let lastReportSize = 0

  // Ensure directory exists
  const dir = path.dirname(filePath)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  const writeStream = fs.createWriteStream(filePath)

  response.on('data', (chunk) => {
    downloadedSize += chunk.length
    writeStream.write(chunk)

    // Report progress every 200ms
    const now = Date.now()
    if (now - lastReportTime >= 200) {
      const speed = (downloadedSize - lastReportSize) / ((now - lastReportTime) / 1000)
      lastReportSize = downloadedSize
      lastReportTime = now

      if (mainWindow && !mainWindow.isDestroyed()) {
        mainWindow.webContents.send('download:progress', {
          filePath,
          downloadedSize,
          totalSize,
          speed,
        })
      }
    }
  })

  response.on('end', () => {
    writeStream.end()
    resolve({
      success: true,
      filePath,
      size: downloadedSize,
    })
  })

  response.on('error', (err) => {
    writeStream.close()
    // Clean up partial file
    try { fs.unlinkSync(filePath) } catch {}
    resolve({ success: false, error: err.message })
  })

  writeStream.on('error', (err) => {
    response.destroy()
    try { fs.unlinkSync(filePath) } catch {}
    resolve({ success: false, error: err.message })
  })
}

/* ── IPC handlers: FFmpeg merge ── */

/**
 * Merge video + audio streams into a single MP4 file using FFmpeg.
 *
 * Input: { videoPath, audioPath, outputPath }
 * Output: { success, outputPath, error? }
 */
ipcMain.handle('ffmpeg:merge', async (_event, { videoPath, audioPath, outputPath }) => {
  return new Promise((resolve) => {
    // Find ffmpeg — check common locations
    const ffmpegPath = findFfmpeg()

    const args = [
      '-i', videoPath,
      '-i', audioPath,
      '-c:v', 'copy',       // Copy video codec (fast, no re-encode)
      '-c:a', 'aac',         // Re-encode audio to AAC (compatible with MP4)
      '-b:a', '192k',        // Audio bitrate
      '-movflags', '+faststart', // Web-optimized
      '-y',                   // Overwrite output
      outputPath,
    ]

    console.log(`[FFmpeg] ${ffmpegPath} ${args.join(' ')}`)

    const ffmpeg = spawn(ffmpegPath, args, {
      stdio: ['pipe', 'pipe', 'pipe'],
    })

    let stderr = ''

    ffmpeg.stderr.on('data', (data) => {
      stderr += data.toString()
    })

    ffmpeg.on('close', (code) => {
      if (code === 0) {
        // Clean up temp files
        try { fs.unlinkSync(videoPath) } catch {}
        try { fs.unlinkSync(audioPath) } catch {}
        resolve({ success: true, outputPath })
      } else {
        console.error(`[FFmpeg] exit code ${code}: ${stderr}`)
        resolve({ success: false, error: `FFmpeg 合并失败 (exit ${code})` })
      }
    })

    ffmpeg.on('error', (err) => {
      console.error(`[FFmpeg] spawn error:`, err)
      resolve({ success: false, error: `无法启动 FFmpeg: ${err.message}` })
    })
  })
})

/**
 * Check if FFmpeg is available on the system.
 */
ipcMain.handle('ffmpeg:check', async () => {
  const found = findFfmpeg()
  if (!found) return { available: false, path: '' }

  // Test that it actually works
  return new Promise((resolve) => {
    const ffmpeg = spawn(found, ['-version'], { stdio: 'pipe' })
    ffmpeg.on('close', (code) => {
      resolve({ available: code === 0, path: found })
    })
    ffmpeg.on('error', () => {
      resolve({ available: false, path: '' })
    })
  })
})

/**
 * Find ffmpeg executable on the system.
 * Checks: bundled ffmpeg, PATH, common install locations.
 */
function findFfmpeg() {
  // 1. Check bundled ffmpeg (in app resources)
  const bundledPath = path.join(
    process.resourcesPath || app.getAppPath(),
    'ffmpeg',
    process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg'
  )
  if (fs.existsSync(bundledPath)) return bundledPath

  // 2. Check same directory as the app
  const appDir = path.dirname(app.getPath('exe'))
  const appDirFfmpeg = path.join(appDir, process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg')
  if (fs.existsSync(appDirFfmpeg)) return appDirFfmpeg

  // 3. Check common Windows locations
  if (process.platform === 'win32') {
    const commonPaths = [
      'C:\\ffmpeg\\bin\\ffmpeg.exe',
      'C:\\Program Files\\ffmpeg\\bin\\ffmpeg.exe',
      path.join(process.env.LOCALAPPDATA || '', 'ffmpeg', 'ffmpeg.exe'),
      path.join(process.resourcesPath || '', 'ffmpeg', 'ffmpeg.exe'),
    ]
    for (const p of commonPaths) {
      if (fs.existsSync(p)) return p
    }
  }

  // 4. Fall back to PATH
  return process.platform === 'win32' ? 'ffmpeg.exe' : 'ffmpeg'
}

/* ── IPC handlers: temp directory ── */

/**
 * Get the app's temp directory for intermediate downloads.
 */
ipcMain.handle('app:getTempDir', () => {
  const tempDir = path.join(app.getPath('temp'), 'bilibilidown')
  if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir, { recursive: true })
  }
  return tempDir
})

/* ── IPC handlers: file operations ── */

/**
 * Move/rename a file from one path to another.
 */
ipcMain.handle('file:move', async (_event, { from, to }) => {
  try {
    // Ensure target directory exists
    const targetDir = path.dirname(to)
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true })
    }
    fs.renameSync(from, to)
    return { success: true }
  } catch (err) {
    // If rename fails (e.g., across drives), try copy + delete
    try {
      fs.copyFileSync(from, to)
      fs.unlinkSync(from)
      return { success: true }
    } catch (copyErr) {
      return { success: false, error: copyErr.message }
    }
  }
})

/* ── IPC handlers: get download path ── */

ipcMain.handle('app:getDownloadPath', () => {
  return app.getPath('downloads')
})

/* ── App menu ── */

const menuTemplate = [
  {
    label: 'BilibiliDown',
    submenu: [
      { role: 'about' },
      { type: 'separator' },
      { role: 'quit' },
    ],
  },
  {
    label: '编辑',
    submenu: [
      { role: 'undo' }, { role: 'redo' },
      { type: 'separator' },
      { role: 'cut' }, { role: 'copy' }, { role: 'paste' },
      { role: 'selectAll' },
    ],
  },
  {
    label: '视图',
    submenu: [
      { role: 'reload' }, { role: 'forceReload' },
      { role: 'toggleDevTools' },
      { type: 'separator' },
      { role: 'resetZoom' }, { role: 'zoomIn' }, { role: 'zoomOut' },
    ],
  },
]

/* ── App lifecycle ── */

app.whenReady().then(() => {
  Menu.setApplicationMenu(Menu.buildFromTemplate(menuTemplate))
  createWindow()
  createTray()

  app.on('activate', () => {
    // macOS: re-create window when dock icon clicked
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
    else showAndFocusWindow()
  })
})

app.on('window-all-closed', () => {
  // Don't quit — the app lives in the system tray
  // Only quit when isQuitting is set (via tray menu "退出" or app:quit IPC)
})

app.on('before-quit', () => {
  isQuitting = true
})

/* ── Prevent multiple instances ── */

const gotLock = app.requestSingleInstanceLock()
if (!gotLock) {
  app.quit()
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore()
      if (!mainWindow.isVisible()) mainWindow.show()
      mainWindow.focus()
    }
  })
}

/* ── Windows notification support ── */

// Required for Windows 10+ native notifications to work.
// Must match the appId in package.json build config.
app.setAppUserModelId('com.bilibilidown.app')
